package com.example.anifun.data.kotlin;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/src/main/java/com/example/anifun/data/proto/dm.proto

public final class Dm {
  private Dm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code DmColorfulType}
   */
  public enum DmColorfulType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 无
     * </pre>
     *
     * <code>NoneType = 0;</code>
     */
    NoneType(0),
    /**
     * <pre>
     * 渐变色
     * </pre>
     *
     * <code>VipGradualColor = 60001;</code>
     */
    VipGradualColor(60001),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 无
     * </pre>
     *
     * <code>NoneType = 0;</code>
     */
    public static final int NoneType_VALUE = 0;
    /**
     * <pre>
     * 渐变色
     * </pre>
     *
     * <code>VipGradualColor = 60001;</code>
     */
    public static final int VipGradualColor_VALUE = 60001;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DmColorfulType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DmColorfulType forNumber(int value) {
      switch (value) {
        case 0: return NoneType;
        case 60001: return VipGradualColor;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DmColorfulType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DmColorfulType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DmColorfulType>() {
            public DmColorfulType findValueByNumber(int number) {
              return DmColorfulType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Dm.getDescriptor().getEnumTypes().get(0);
    }

    private static final DmColorfulType[] VALUES = values();

    public static DmColorfulType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DmColorfulType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DmColorfulType)
  }

  public interface DanmakuElemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DanmakuElem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 弹幕dmid
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     * 弹幕出现位置(单位ms)
     * </pre>
     *
     * <code>int32 progress = 2;</code>
     * @return The progress.
     */
    int getProgress();

    /**
     * <pre>
     * 弹幕类型 1 2 3:普通弹幕 4:底部弹幕 5:顶部弹幕 6:逆向弹幕 7:高级弹幕 8:代码弹幕 9:BAS弹幕(pool必须为2)
     * </pre>
     *
     * <code>int32 mode = 3;</code>
     * @return The mode.
     */
    int getMode();

    /**
     * <pre>
     * 弹幕字号
     * </pre>
     *
     * <code>int32 fontsize = 4;</code>
     * @return The fontsize.
     */
    int getFontsize();

    /**
     * <pre>
     * 弹幕颜色
     * </pre>
     *
     * <code>uint32 color = 5;</code>
     * @return The color.
     */
    int getColor();

    /**
     * <pre>
     * 发送着mid hash
     * </pre>
     *
     * <code>string midHash = 6;</code>
     * @return The midHash.
     */
    java.lang.String getMidHash();
    /**
     * <pre>
     * 发送着mid hash
     * </pre>
     *
     * <code>string midHash = 6;</code>
     * @return The bytes for midHash.
     */
    com.google.protobuf.ByteString
        getMidHashBytes();

    /**
     * <pre>
     * 弹幕正文
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 弹幕正文
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>int64 ctime = 8;</code>
     * @return The ctime.
     */
    long getCtime();

    /**
     * <pre>
     * 权重 用于屏蔽等级 区间:[1,10]
     * </pre>
     *
     * <code>int32 weight = 9;</code>
     * @return The weight.
     */
    int getWeight();

    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>string action = 10;</code>
     * @return The action.
     */
    java.lang.String getAction();
    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>string action = 10;</code>
     * @return The bytes for action.
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <pre>
     * 弹幕池 0:普通池 1:字幕池 2:特殊池(代码/BAS弹幕)
     * </pre>
     *
     * <code>int32 pool = 11;</code>
     * @return The pool.
     */
    int getPool();

    /**
     * <pre>
     * 弹幕dmid str
     * </pre>
     *
     * <code>string idStr = 12;</code>
     * @return The idStr.
     */
    java.lang.String getIdStr();
    /**
     * <pre>
     * 弹幕dmid str
     * </pre>
     *
     * <code>string idStr = 12;</code>
     * @return The bytes for idStr.
     */
    com.google.protobuf.ByteString
        getIdStrBytes();

    /**
     * <pre>
     * 弹幕属性位(bin求AND)
     * bit0:保护 bit1:直播 bit2:高赞
     * </pre>
     *
     * <code>int32 attr = 13;</code>
     * @return The attr.
     */
    int getAttr();

    /**
     * <pre>
     * </pre>
     *
     * <code>string animation = 22;</code>
     * @return The animation.
     */
    java.lang.String getAnimation();
    /**
     * <pre>
     * </pre>
     *
     * <code>string animation = 22;</code>
     * @return The bytes for animation.
     */
    com.google.protobuf.ByteString
        getAnimationBytes();

    /**
     * <pre>
     * 大会员专属颜色
     * </pre>
     *
     * <code>.DmColorfulType colorful = 24;</code>
     * @return The enum numeric value on the wire for colorful.
     */
    int getColorfulValue();
    /**
     * <pre>
     * 大会员专属颜色
     * </pre>
     *
     * <code>.DmColorfulType colorful = 24;</code>
     * @return The colorful.
     */
    Dm.DmColorfulType getColorful();
  }
  /**
   * <pre>
   * 弹幕条目
   * </pre>
   *
   * Protobuf type {@code DanmakuElem}
   */
  public static final class DanmakuElem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DanmakuElem)
      DanmakuElemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DanmakuElem.newBuilder() to construct.
    private DanmakuElem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DanmakuElem() {
      midHash_ = "";
      content_ = "";
      action_ = "";
      idStr_ = "";
      animation_ = "";
      colorful_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DanmakuElem();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Dm.internal_static_DanmakuElem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Dm.internal_static_DanmakuElem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Dm.DanmakuElem.class, Dm.DanmakuElem.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <pre>
     * 弹幕dmid
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int PROGRESS_FIELD_NUMBER = 2;
    private int progress_ = 0;
    /**
     * <pre>
     * 弹幕出现位置(单位ms)
     * </pre>
     *
     * <code>int32 progress = 2;</code>
     * @return The progress.
     */
    @java.lang.Override
    public int getProgress() {
      return progress_;
    }

    public static final int MODE_FIELD_NUMBER = 3;
    private int mode_ = 0;
    /**
     * <pre>
     * 弹幕类型 1 2 3:普通弹幕 4:底部弹幕 5:顶部弹幕 6:逆向弹幕 7:高级弹幕 8:代码弹幕 9:BAS弹幕(pool必须为2)
     * </pre>
     *
     * <code>int32 mode = 3;</code>
     * @return The mode.
     */
    @java.lang.Override
    public int getMode() {
      return mode_;
    }

    public static final int FONTSIZE_FIELD_NUMBER = 4;
    private int fontsize_ = 0;
    /**
     * <pre>
     * 弹幕字号
     * </pre>
     *
     * <code>int32 fontsize = 4;</code>
     * @return The fontsize.
     */
    @java.lang.Override
    public int getFontsize() {
      return fontsize_;
    }

    public static final int COLOR_FIELD_NUMBER = 5;
    private int color_ = 0;
    /**
     * <pre>
     * 弹幕颜色
     * </pre>
     *
     * <code>uint32 color = 5;</code>
     * @return The color.
     */
    @java.lang.Override
    public int getColor() {
      return color_;
    }

    public static final int MIDHASH_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object midHash_ = "";
    /**
     * <pre>
     * 发送着mid hash
     * </pre>
     *
     * <code>string midHash = 6;</code>
     * @return The midHash.
     */
    @java.lang.Override
    public java.lang.String getMidHash() {
      java.lang.Object ref = midHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        midHash_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送着mid hash
     * </pre>
     *
     * <code>string midHash = 6;</code>
     * @return The bytes for midHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMidHashBytes() {
      java.lang.Object ref = midHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        midHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";
    /**
     * <pre>
     * 弹幕正文
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 弹幕正文
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CTIME_FIELD_NUMBER = 8;
    private long ctime_ = 0L;
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>int64 ctime = 8;</code>
     * @return The ctime.
     */
    @java.lang.Override
    public long getCtime() {
      return ctime_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 9;
    private int weight_ = 0;
    /**
     * <pre>
     * 权重 用于屏蔽等级 区间:[1,10]
     * </pre>
     *
     * <code>int32 weight = 9;</code>
     * @return The weight.
     */
    @java.lang.Override
    public int getWeight() {
      return weight_;
    }

    public static final int ACTION_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object action_ = "";
    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>string action = 10;</code>
     * @return The action.
     */
    @java.lang.Override
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>string action = 10;</code>
     * @return The bytes for action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POOL_FIELD_NUMBER = 11;
    private int pool_ = 0;
    /**
     * <pre>
     * 弹幕池 0:普通池 1:字幕池 2:特殊池(代码/BAS弹幕)
     * </pre>
     *
     * <code>int32 pool = 11;</code>
     * @return The pool.
     */
    @java.lang.Override
    public int getPool() {
      return pool_;
    }

    public static final int IDSTR_FIELD_NUMBER = 12;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idStr_ = "";
    /**
     * <pre>
     * 弹幕dmid str
     * </pre>
     *
     * <code>string idStr = 12;</code>
     * @return The idStr.
     */
    @java.lang.Override
    public java.lang.String getIdStr() {
      java.lang.Object ref = idStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idStr_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 弹幕dmid str
     * </pre>
     *
     * <code>string idStr = 12;</code>
     * @return The bytes for idStr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdStrBytes() {
      java.lang.Object ref = idStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTR_FIELD_NUMBER = 13;
    private int attr_ = 0;
    /**
     * <pre>
     * 弹幕属性位(bin求AND)
     * bit0:保护 bit1:直播 bit2:高赞
     * </pre>
     *
     * <code>int32 attr = 13;</code>
     * @return The attr.
     */
    @java.lang.Override
    public int getAttr() {
      return attr_;
    }

    public static final int ANIMATION_FIELD_NUMBER = 22;
    @SuppressWarnings("serial")
    private volatile java.lang.Object animation_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string animation = 22;</code>
     * @return The animation.
     */
    @java.lang.Override
    public java.lang.String getAnimation() {
      java.lang.Object ref = animation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        animation_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string animation = 22;</code>
     * @return The bytes for animation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAnimationBytes() {
      java.lang.Object ref = animation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        animation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLORFUL_FIELD_NUMBER = 24;
    private int colorful_ = 0;
    /**
     * <pre>
     * 大会员专属颜色
     * </pre>
     *
     * <code>.DmColorfulType colorful = 24;</code>
     * @return The enum numeric value on the wire for colorful.
     */
    @java.lang.Override public int getColorfulValue() {
      return colorful_;
    }
    /**
     * <pre>
     * 大会员专属颜色
     * </pre>
     *
     * <code>.DmColorfulType colorful = 24;</code>
     * @return The colorful.
     */
    @java.lang.Override public Dm.DmColorfulType getColorful() {
      Dm.DmColorfulType result = Dm.DmColorfulType.forNumber(colorful_);
      return result == null ? Dm.DmColorfulType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (progress_ != 0) {
        output.writeInt32(2, progress_);
      }
      if (mode_ != 0) {
        output.writeInt32(3, mode_);
      }
      if (fontsize_ != 0) {
        output.writeInt32(4, fontsize_);
      }
      if (color_ != 0) {
        output.writeUInt32(5, color_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(midHash_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, midHash_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, content_);
      }
      if (ctime_ != 0L) {
        output.writeInt64(8, ctime_);
      }
      if (weight_ != 0) {
        output.writeInt32(9, weight_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, action_);
      }
      if (pool_ != 0) {
        output.writeInt32(11, pool_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idStr_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, idStr_);
      }
      if (attr_ != 0) {
        output.writeInt32(13, attr_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(animation_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 22, animation_);
      }
      if (colorful_ != Dm.DmColorfulType.NoneType.getNumber()) {
        output.writeEnum(24, colorful_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (progress_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, progress_);
      }
      if (mode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, mode_);
      }
      if (fontsize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, fontsize_);
      }
      if (color_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, color_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(midHash_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, midHash_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, content_);
      }
      if (ctime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, ctime_);
      }
      if (weight_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, weight_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, action_);
      }
      if (pool_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, pool_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idStr_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, idStr_);
      }
      if (attr_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, attr_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(animation_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(22, animation_);
      }
      if (colorful_ != Dm.DmColorfulType.NoneType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(24, colorful_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Dm.DanmakuElem)) {
        return super.equals(obj);
      }
      Dm.DanmakuElem other = (Dm.DanmakuElem) obj;

      if (getId()
          != other.getId()) return false;
      if (getProgress()
          != other.getProgress()) return false;
      if (getMode()
          != other.getMode()) return false;
      if (getFontsize()
          != other.getFontsize()) return false;
      if (getColor()
          != other.getColor()) return false;
      if (!getMidHash()
          .equals(other.getMidHash())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getCtime()
          != other.getCtime()) return false;
      if (getWeight()
          != other.getWeight()) return false;
      if (!getAction()
          .equals(other.getAction())) return false;
      if (getPool()
          != other.getPool()) return false;
      if (!getIdStr()
          .equals(other.getIdStr())) return false;
      if (getAttr()
          != other.getAttr()) return false;
      if (!getAnimation()
          .equals(other.getAnimation())) return false;
      if (colorful_ != other.colorful_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
      hash = (53 * hash) + getProgress();
      hash = (37 * hash) + MODE_FIELD_NUMBER;
      hash = (53 * hash) + getMode();
      hash = (37 * hash) + FONTSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getFontsize();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor();
      hash = (37 * hash) + MIDHASH_FIELD_NUMBER;
      hash = (53 * hash) + getMidHash().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCtime());
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getWeight();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + POOL_FIELD_NUMBER;
      hash = (53 * hash) + getPool();
      hash = (37 * hash) + IDSTR_FIELD_NUMBER;
      hash = (53 * hash) + getIdStr().hashCode();
      hash = (37 * hash) + ATTR_FIELD_NUMBER;
      hash = (53 * hash) + getAttr();
      hash = (37 * hash) + ANIMATION_FIELD_NUMBER;
      hash = (53 * hash) + getAnimation().hashCode();
      hash = (37 * hash) + COLORFUL_FIELD_NUMBER;
      hash = (53 * hash) + colorful_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Dm.DanmakuElem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dm.DanmakuElem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dm.DanmakuElem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dm.DanmakuElem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dm.DanmakuElem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dm.DanmakuElem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dm.DanmakuElem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dm.DanmakuElem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Dm.DanmakuElem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Dm.DanmakuElem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Dm.DanmakuElem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dm.DanmakuElem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Dm.DanmakuElem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 弹幕条目
     * </pre>
     *
     * Protobuf type {@code DanmakuElem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DanmakuElem)
        Dm.DanmakuElemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Dm.internal_static_DanmakuElem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Dm.internal_static_DanmakuElem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Dm.DanmakuElem.class, Dm.DanmakuElem.Builder.class);
      }

      // Construct using Dm.DanmakuElem.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        progress_ = 0;
        mode_ = 0;
        fontsize_ = 0;
        color_ = 0;
        midHash_ = "";
        content_ = "";
        ctime_ = 0L;
        weight_ = 0;
        action_ = "";
        pool_ = 0;
        idStr_ = "";
        attr_ = 0;
        animation_ = "";
        colorful_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Dm.internal_static_DanmakuElem_descriptor;
      }

      @java.lang.Override
      public Dm.DanmakuElem getDefaultInstanceForType() {
        return Dm.DanmakuElem.getDefaultInstance();
      }

      @java.lang.Override
      public Dm.DanmakuElem build() {
        Dm.DanmakuElem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Dm.DanmakuElem buildPartial() {
        Dm.DanmakuElem result = new Dm.DanmakuElem(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Dm.DanmakuElem result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.progress_ = progress_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.mode_ = mode_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.fontsize_ = fontsize_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.color_ = color_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.midHash_ = midHash_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.ctime_ = ctime_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.weight_ = weight_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.action_ = action_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.pool_ = pool_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.idStr_ = idStr_;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.attr_ = attr_;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.animation_ = animation_;
        }
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.colorful_ = colorful_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Dm.DanmakuElem) {
          return mergeFrom((Dm.DanmakuElem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Dm.DanmakuElem other) {
        if (other == Dm.DanmakuElem.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getProgress() != 0) {
          setProgress(other.getProgress());
        }
        if (other.getMode() != 0) {
          setMode(other.getMode());
        }
        if (other.getFontsize() != 0) {
          setFontsize(other.getFontsize());
        }
        if (other.getColor() != 0) {
          setColor(other.getColor());
        }
        if (!other.getMidHash().isEmpty()) {
          midHash_ = other.midHash_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.getCtime() != 0L) {
          setCtime(other.getCtime());
        }
        if (other.getWeight() != 0) {
          setWeight(other.getWeight());
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (other.getPool() != 0) {
          setPool(other.getPool());
        }
        if (!other.getIdStr().isEmpty()) {
          idStr_ = other.idStr_;
          bitField0_ |= 0x00000800;
          onChanged();
        }
        if (other.getAttr() != 0) {
          setAttr(other.getAttr());
        }
        if (!other.getAnimation().isEmpty()) {
          animation_ = other.animation_;
          bitField0_ |= 0x00002000;
          onChanged();
        }
        if (other.colorful_ != 0) {
          setColorfulValue(other.getColorfulValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                progress_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                mode_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                fontsize_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                color_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                midHash_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                ctime_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                weight_ = input.readInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 82: {
                action_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 88: {
                pool_ = input.readInt32();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              case 98: {
                idStr_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000800;
                break;
              } // case 98
              case 104: {
                attr_ = input.readInt32();
                bitField0_ |= 0x00001000;
                break;
              } // case 104
              case 178: {
                animation_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00002000;
                break;
              } // case 178
              case 192: {
                colorful_ = input.readEnum();
                bitField0_ |= 0x00004000;
                break;
              } // case 192
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       * 弹幕dmid
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * 弹幕dmid
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 弹幕dmid
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private int progress_ ;
      /**
       * <pre>
       * 弹幕出现位置(单位ms)
       * </pre>
       *
       * <code>int32 progress = 2;</code>
       * @return The progress.
       */
      @java.lang.Override
      public int getProgress() {
        return progress_;
      }
      /**
       * <pre>
       * 弹幕出现位置(单位ms)
       * </pre>
       *
       * <code>int32 progress = 2;</code>
       * @param value The progress to set.
       * @return This builder for chaining.
       */
      public Builder setProgress(int value) {

        progress_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 弹幕出现位置(单位ms)
       * </pre>
       *
       * <code>int32 progress = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProgress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        progress_ = 0;
        onChanged();
        return this;
      }

      private int mode_ ;
      /**
       * <pre>
       * 弹幕类型 1 2 3:普通弹幕 4:底部弹幕 5:顶部弹幕 6:逆向弹幕 7:高级弹幕 8:代码弹幕 9:BAS弹幕(pool必须为2)
       * </pre>
       *
       * <code>int32 mode = 3;</code>
       * @return The mode.
       */
      @java.lang.Override
      public int getMode() {
        return mode_;
      }
      /**
       * <pre>
       * 弹幕类型 1 2 3:普通弹幕 4:底部弹幕 5:顶部弹幕 6:逆向弹幕 7:高级弹幕 8:代码弹幕 9:BAS弹幕(pool必须为2)
       * </pre>
       *
       * <code>int32 mode = 3;</code>
       * @param value The mode to set.
       * @return This builder for chaining.
       */
      public Builder setMode(int value) {

        mode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 弹幕类型 1 2 3:普通弹幕 4:底部弹幕 5:顶部弹幕 6:逆向弹幕 7:高级弹幕 8:代码弹幕 9:BAS弹幕(pool必须为2)
       * </pre>
       *
       * <code>int32 mode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mode_ = 0;
        onChanged();
        return this;
      }

      private int fontsize_ ;
      /**
       * <pre>
       * 弹幕字号
       * </pre>
       *
       * <code>int32 fontsize = 4;</code>
       * @return The fontsize.
       */
      @java.lang.Override
      public int getFontsize() {
        return fontsize_;
      }
      /**
       * <pre>
       * 弹幕字号
       * </pre>
       *
       * <code>int32 fontsize = 4;</code>
       * @param value The fontsize to set.
       * @return This builder for chaining.
       */
      public Builder setFontsize(int value) {

        fontsize_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 弹幕字号
       * </pre>
       *
       * <code>int32 fontsize = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFontsize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fontsize_ = 0;
        onChanged();
        return this;
      }

      private int color_ ;
      /**
       * <pre>
       * 弹幕颜色
       * </pre>
       *
       * <code>uint32 color = 5;</code>
       * @return The color.
       */
      @java.lang.Override
      public int getColor() {
        return color_;
      }
      /**
       * <pre>
       * 弹幕颜色
       * </pre>
       *
       * <code>uint32 color = 5;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(int value) {

        color_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 弹幕颜色
       * </pre>
       *
       * <code>uint32 color = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000010);
        color_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object midHash_ = "";
      /**
       * <pre>
       * 发送着mid hash
       * </pre>
       *
       * <code>string midHash = 6;</code>
       * @return The midHash.
       */
      public java.lang.String getMidHash() {
        java.lang.Object ref = midHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          midHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 发送着mid hash
       * </pre>
       *
       * <code>string midHash = 6;</code>
       * @return The bytes for midHash.
       */
      public com.google.protobuf.ByteString
          getMidHashBytes() {
        java.lang.Object ref = midHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          midHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送着mid hash
       * </pre>
       *
       * <code>string midHash = 6;</code>
       * @param value The midHash to set.
       * @return This builder for chaining.
       */
      public Builder setMidHash(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        midHash_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送着mid hash
       * </pre>
       *
       * <code>string midHash = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMidHash() {
        midHash_ = getDefaultInstance().getMidHash();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送着mid hash
       * </pre>
       *
       * <code>string midHash = 6;</code>
       * @param value The bytes for midHash to set.
       * @return This builder for chaining.
       */
      public Builder setMidHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        midHash_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 弹幕正文
       * </pre>
       *
       * <code>string content = 7;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 弹幕正文
       * </pre>
       *
       * <code>string content = 7;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 弹幕正文
       * </pre>
       *
       * <code>string content = 7;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 弹幕正文
       * </pre>
       *
       * <code>string content = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 弹幕正文
       * </pre>
       *
       * <code>string content = 7;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private long ctime_ ;
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>int64 ctime = 8;</code>
       * @return The ctime.
       */
      @java.lang.Override
      public long getCtime() {
        return ctime_;
      }
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>int64 ctime = 8;</code>
       * @param value The ctime to set.
       * @return This builder for chaining.
       */
      public Builder setCtime(long value) {

        ctime_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>int64 ctime = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCtime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ctime_ = 0L;
        onChanged();
        return this;
      }

      private int weight_ ;
      /**
       * <pre>
       * 权重 用于屏蔽等级 区间:[1,10]
       * </pre>
       *
       * <code>int32 weight = 9;</code>
       * @return The weight.
       */
      @java.lang.Override
      public int getWeight() {
        return weight_;
      }
      /**
       * <pre>
       * 权重 用于屏蔽等级 区间:[1,10]
       * </pre>
       *
       * <code>int32 weight = 9;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(int value) {

        weight_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 权重 用于屏蔽等级 区间:[1,10]
       * </pre>
       *
       * <code>int32 weight = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000100);
        weight_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <pre>
       * 动作
       * </pre>
       *
       * <code>string action = 10;</code>
       * @return The action.
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 动作
       * </pre>
       *
       * <code>string action = 10;</code>
       * @return The bytes for action.
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 动作
       * </pre>
       *
       * <code>string action = 10;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        action_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 动作
       * </pre>
       *
       * <code>string action = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        action_ = getDefaultInstance().getAction();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 动作
       * </pre>
       *
       * <code>string action = 10;</code>
       * @param value The bytes for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        action_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private int pool_ ;
      /**
       * <pre>
       * 弹幕池 0:普通池 1:字幕池 2:特殊池(代码/BAS弹幕)
       * </pre>
       *
       * <code>int32 pool = 11;</code>
       * @return The pool.
       */
      @java.lang.Override
      public int getPool() {
        return pool_;
      }
      /**
       * <pre>
       * 弹幕池 0:普通池 1:字幕池 2:特殊池(代码/BAS弹幕)
       * </pre>
       *
       * <code>int32 pool = 11;</code>
       * @param value The pool to set.
       * @return This builder for chaining.
       */
      public Builder setPool(int value) {

        pool_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 弹幕池 0:普通池 1:字幕池 2:特殊池(代码/BAS弹幕)
       * </pre>
       *
       * <code>int32 pool = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearPool() {
        bitField0_ = (bitField0_ & ~0x00000400);
        pool_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object idStr_ = "";
      /**
       * <pre>
       * 弹幕dmid str
       * </pre>
       *
       * <code>string idStr = 12;</code>
       * @return The idStr.
       */
      public java.lang.String getIdStr() {
        java.lang.Object ref = idStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 弹幕dmid str
       * </pre>
       *
       * <code>string idStr = 12;</code>
       * @return The bytes for idStr.
       */
      public com.google.protobuf.ByteString
          getIdStrBytes() {
        java.lang.Object ref = idStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 弹幕dmid str
       * </pre>
       *
       * <code>string idStr = 12;</code>
       * @param value The idStr to set.
       * @return This builder for chaining.
       */
      public Builder setIdStr(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idStr_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 弹幕dmid str
       * </pre>
       *
       * <code>string idStr = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdStr() {
        idStr_ = getDefaultInstance().getIdStr();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 弹幕dmid str
       * </pre>
       *
       * <code>string idStr = 12;</code>
       * @param value The bytes for idStr to set.
       * @return This builder for chaining.
       */
      public Builder setIdStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idStr_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }

      private int attr_ ;
      /**
       * <pre>
       * 弹幕属性位(bin求AND)
       * bit0:保护 bit1:直播 bit2:高赞
       * </pre>
       *
       * <code>int32 attr = 13;</code>
       * @return The attr.
       */
      @java.lang.Override
      public int getAttr() {
        return attr_;
      }
      /**
       * <pre>
       * 弹幕属性位(bin求AND)
       * bit0:保护 bit1:直播 bit2:高赞
       * </pre>
       *
       * <code>int32 attr = 13;</code>
       * @param value The attr to set.
       * @return This builder for chaining.
       */
      public Builder setAttr(int value) {

        attr_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 弹幕属性位(bin求AND)
       * bit0:保护 bit1:直播 bit2:高赞
       * </pre>
       *
       * <code>int32 attr = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttr() {
        bitField0_ = (bitField0_ & ~0x00001000);
        attr_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object animation_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>string animation = 22;</code>
       * @return The animation.
       */
      public java.lang.String getAnimation() {
        java.lang.Object ref = animation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          animation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string animation = 22;</code>
       * @return The bytes for animation.
       */
      public com.google.protobuf.ByteString
          getAnimationBytes() {
        java.lang.Object ref = animation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          animation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string animation = 22;</code>
       * @param value The animation to set.
       * @return This builder for chaining.
       */
      public Builder setAnimation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        animation_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string animation = 22;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnimation() {
        animation_ = getDefaultInstance().getAnimation();
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string animation = 22;</code>
       * @param value The bytes for animation to set.
       * @return This builder for chaining.
       */
      public Builder setAnimationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        animation_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }

      private int colorful_ = 0;
      /**
       * <pre>
       * 大会员专属颜色
       * </pre>
       *
       * <code>.DmColorfulType colorful = 24;</code>
       * @return The enum numeric value on the wire for colorful.
       */
      @java.lang.Override public int getColorfulValue() {
        return colorful_;
      }
      /**
       * <pre>
       * 大会员专属颜色
       * </pre>
       *
       * <code>.DmColorfulType colorful = 24;</code>
       * @param value The enum numeric value on the wire for colorful to set.
       * @return This builder for chaining.
       */
      public Builder setColorfulValue(int value) {
        colorful_ = value;
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 大会员专属颜色
       * </pre>
       *
       * <code>.DmColorfulType colorful = 24;</code>
       * @return The colorful.
       */
      @java.lang.Override
      public Dm.DmColorfulType getColorful() {
        Dm.DmColorfulType result = Dm.DmColorfulType.forNumber(colorful_);
        return result == null ? Dm.DmColorfulType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 大会员专属颜色
       * </pre>
       *
       * <code>.DmColorfulType colorful = 24;</code>
       * @param value The colorful to set.
       * @return This builder for chaining.
       */
      public Builder setColorful(Dm.DmColorfulType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00004000;
        colorful_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 大会员专属颜色
       * </pre>
       *
       * <code>.DmColorfulType colorful = 24;</code>
       * @return This builder for chaining.
       */
      public Builder clearColorful() {
        bitField0_ = (bitField0_ & ~0x00004000);
        colorful_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DanmakuElem)
    }

    // @@protoc_insertion_point(class_scope:DanmakuElem)
    private static final Dm.DanmakuElem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Dm.DanmakuElem();
    }

    public static Dm.DanmakuElem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DanmakuElem>
        PARSER = new com.google.protobuf.AbstractParser<DanmakuElem>() {
      @java.lang.Override
      public DanmakuElem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DanmakuElem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DanmakuElem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Dm.DanmakuElem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DmSegMobileReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DmSegMobileReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 弹幕列表
     * </pre>
     *
     * <code>repeated .DanmakuElem elems = 1;</code>
     */
    java.util.List<Dm.DanmakuElem> 
        getElemsList();
    /**
     * <pre>
     * 弹幕列表
     * </pre>
     *
     * <code>repeated .DanmakuElem elems = 1;</code>
     */
    Dm.DanmakuElem getElems(int index);
    /**
     * <pre>
     * 弹幕列表
     * </pre>
     *
     * <code>repeated .DanmakuElem elems = 1;</code>
     */
    int getElemsCount();
    /**
     * <pre>
     * 弹幕列表
     * </pre>
     *
     * <code>repeated .DanmakuElem elems = 1;</code>
     */
    java.util.List<? extends Dm.DanmakuElemOrBuilder> 
        getElemsOrBuilderList();
    /**
     * <pre>
     * 弹幕列表
     * </pre>
     *
     * <code>repeated .DanmakuElem elems = 1;</code>
     */
    Dm.DanmakuElemOrBuilder getElemsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 获取弹幕-响应
   * </pre>
   *
   * Protobuf type {@code DmSegMobileReply}
   */
  public static final class DmSegMobileReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DmSegMobileReply)
      DmSegMobileReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DmSegMobileReply.newBuilder() to construct.
    private DmSegMobileReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DmSegMobileReply() {
      elems_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DmSegMobileReply();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Dm.internal_static_DmSegMobileReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Dm.internal_static_DmSegMobileReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Dm.DmSegMobileReply.class, Dm.DmSegMobileReply.Builder.class);
    }

    public static final int ELEMS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<Dm.DanmakuElem> elems_;
    /**
     * <pre>
     * 弹幕列表
     * </pre>
     *
     * <code>repeated .DanmakuElem elems = 1;</code>
     */
    @java.lang.Override
    public java.util.List<Dm.DanmakuElem> getElemsList() {
      return elems_;
    }
    /**
     * <pre>
     * 弹幕列表
     * </pre>
     *
     * <code>repeated .DanmakuElem elems = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Dm.DanmakuElemOrBuilder> 
        getElemsOrBuilderList() {
      return elems_;
    }
    /**
     * <pre>
     * 弹幕列表
     * </pre>
     *
     * <code>repeated .DanmakuElem elems = 1;</code>
     */
    @java.lang.Override
    public int getElemsCount() {
      return elems_.size();
    }
    /**
     * <pre>
     * 弹幕列表
     * </pre>
     *
     * <code>repeated .DanmakuElem elems = 1;</code>
     */
    @java.lang.Override
    public Dm.DanmakuElem getElems(int index) {
      return elems_.get(index);
    }
    /**
     * <pre>
     * 弹幕列表
     * </pre>
     *
     * <code>repeated .DanmakuElem elems = 1;</code>
     */
    @java.lang.Override
    public Dm.DanmakuElemOrBuilder getElemsOrBuilder(
        int index) {
      return elems_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < elems_.size(); i++) {
        output.writeMessage(1, elems_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < elems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, elems_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Dm.DmSegMobileReply)) {
        return super.equals(obj);
      }
      Dm.DmSegMobileReply other = (Dm.DmSegMobileReply) obj;

      if (!getElemsList()
          .equals(other.getElemsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getElemsCount() > 0) {
        hash = (37 * hash) + ELEMS_FIELD_NUMBER;
        hash = (53 * hash) + getElemsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Dm.DmSegMobileReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dm.DmSegMobileReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dm.DmSegMobileReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dm.DmSegMobileReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dm.DmSegMobileReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Dm.DmSegMobileReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Dm.DmSegMobileReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dm.DmSegMobileReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Dm.DmSegMobileReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Dm.DmSegMobileReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Dm.DmSegMobileReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Dm.DmSegMobileReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Dm.DmSegMobileReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 获取弹幕-响应
     * </pre>
     *
     * Protobuf type {@code DmSegMobileReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DmSegMobileReply)
        Dm.DmSegMobileReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Dm.internal_static_DmSegMobileReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Dm.internal_static_DmSegMobileReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Dm.DmSegMobileReply.class, Dm.DmSegMobileReply.Builder.class);
      }

      // Construct using Dm.DmSegMobileReply.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (elemsBuilder_ == null) {
          elems_ = java.util.Collections.emptyList();
        } else {
          elems_ = null;
          elemsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Dm.internal_static_DmSegMobileReply_descriptor;
      }

      @java.lang.Override
      public Dm.DmSegMobileReply getDefaultInstanceForType() {
        return Dm.DmSegMobileReply.getDefaultInstance();
      }

      @java.lang.Override
      public Dm.DmSegMobileReply build() {
        Dm.DmSegMobileReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Dm.DmSegMobileReply buildPartial() {
        Dm.DmSegMobileReply result = new Dm.DmSegMobileReply(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Dm.DmSegMobileReply result) {
        if (elemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            elems_ = java.util.Collections.unmodifiableList(elems_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.elems_ = elems_;
        } else {
          result.elems_ = elemsBuilder_.build();
        }
      }

      private void buildPartial0(Dm.DmSegMobileReply result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Dm.DmSegMobileReply) {
          return mergeFrom((Dm.DmSegMobileReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Dm.DmSegMobileReply other) {
        if (other == Dm.DmSegMobileReply.getDefaultInstance()) return this;
        if (elemsBuilder_ == null) {
          if (!other.elems_.isEmpty()) {
            if (elems_.isEmpty()) {
              elems_ = other.elems_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureElemsIsMutable();
              elems_.addAll(other.elems_);
            }
            onChanged();
          }
        } else {
          if (!other.elems_.isEmpty()) {
            if (elemsBuilder_.isEmpty()) {
              elemsBuilder_.dispose();
              elemsBuilder_ = null;
              elems_ = other.elems_;
              bitField0_ = (bitField0_ & ~0x00000001);
              elemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getElemsFieldBuilder() : null;
            } else {
              elemsBuilder_.addAllMessages(other.elems_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                Dm.DanmakuElem m =
                    input.readMessage(
                        Dm.DanmakuElem.parser(),
                        extensionRegistry);
                if (elemsBuilder_ == null) {
                  ensureElemsIsMutable();
                  elems_.add(m);
                } else {
                  elemsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<Dm.DanmakuElem> elems_ =
        java.util.Collections.emptyList();
      private void ensureElemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          elems_ = new java.util.ArrayList<Dm.DanmakuElem>(elems_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Dm.DanmakuElem, Dm.DanmakuElem.Builder, Dm.DanmakuElemOrBuilder> elemsBuilder_;

      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public java.util.List<Dm.DanmakuElem> getElemsList() {
        if (elemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(elems_);
        } else {
          return elemsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public int getElemsCount() {
        if (elemsBuilder_ == null) {
          return elems_.size();
        } else {
          return elemsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Dm.DanmakuElem getElems(int index) {
        if (elemsBuilder_ == null) {
          return elems_.get(index);
        } else {
          return elemsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Builder setElems(
          int index, Dm.DanmakuElem value) {
        if (elemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElemsIsMutable();
          elems_.set(index, value);
          onChanged();
        } else {
          elemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Builder setElems(
          int index, Dm.DanmakuElem.Builder builderForValue) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          elems_.set(index, builderForValue.build());
          onChanged();
        } else {
          elemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Builder addElems(Dm.DanmakuElem value) {
        if (elemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElemsIsMutable();
          elems_.add(value);
          onChanged();
        } else {
          elemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Builder addElems(
          int index, Dm.DanmakuElem value) {
        if (elemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElemsIsMutable();
          elems_.add(index, value);
          onChanged();
        } else {
          elemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Builder addElems(
          Dm.DanmakuElem.Builder builderForValue) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          elems_.add(builderForValue.build());
          onChanged();
        } else {
          elemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Builder addElems(
          int index, Dm.DanmakuElem.Builder builderForValue) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          elems_.add(index, builderForValue.build());
          onChanged();
        } else {
          elemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Builder addAllElems(
          java.lang.Iterable<? extends Dm.DanmakuElem> values) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, elems_);
          onChanged();
        } else {
          elemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Builder clearElems() {
        if (elemsBuilder_ == null) {
          elems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          elemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Builder removeElems(int index) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          elems_.remove(index);
          onChanged();
        } else {
          elemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Dm.DanmakuElem.Builder getElemsBuilder(
          int index) {
        return getElemsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Dm.DanmakuElemOrBuilder getElemsOrBuilder(
          int index) {
        if (elemsBuilder_ == null) {
          return elems_.get(index);  } else {
          return elemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public java.util.List<? extends Dm.DanmakuElemOrBuilder> 
           getElemsOrBuilderList() {
        if (elemsBuilder_ != null) {
          return elemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(elems_);
        }
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Dm.DanmakuElem.Builder addElemsBuilder() {
        return getElemsFieldBuilder().addBuilder(
            Dm.DanmakuElem.getDefaultInstance());
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public Dm.DanmakuElem.Builder addElemsBuilder(
          int index) {
        return getElemsFieldBuilder().addBuilder(
            index, Dm.DanmakuElem.getDefaultInstance());
      }
      /**
       * <pre>
       * 弹幕列表
       * </pre>
       *
       * <code>repeated .DanmakuElem elems = 1;</code>
       */
      public java.util.List<Dm.DanmakuElem.Builder> 
           getElemsBuilderList() {
        return getElemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Dm.DanmakuElem, Dm.DanmakuElem.Builder, Dm.DanmakuElemOrBuilder> 
          getElemsFieldBuilder() {
        if (elemsBuilder_ == null) {
          elemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Dm.DanmakuElem, Dm.DanmakuElem.Builder, Dm.DanmakuElemOrBuilder>(
                  elems_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          elems_ = null;
        }
        return elemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DmSegMobileReply)
    }

    // @@protoc_insertion_point(class_scope:DmSegMobileReply)
    private static final Dm.DmSegMobileReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Dm.DmSegMobileReply();
    }

    public static Dm.DmSegMobileReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DmSegMobileReply>
        PARSER = new com.google.protobuf.AbstractParser<DmSegMobileReply>() {
      @java.lang.Override
      public DmSegMobileReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DmSegMobileReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DmSegMobileReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Dm.DmSegMobileReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DanmakuElem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DanmakuElem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DmSegMobileReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DmSegMobileReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8app/src/main/java/com/example/anifun/d" +
      "ata/proto/dm.proto\"\214\002\n\013DanmakuElem\022\n\n\002id" +
      "\030\001 \001(\003\022\020\n\010progress\030\002 \001(\005\022\014\n\004mode\030\003 \001(\005\022\020" +
      "\n\010fontsize\030\004 \001(\005\022\r\n\005color\030\005 \001(\r\022\017\n\007midHa" +
      "sh\030\006 \001(\t\022\017\n\007content\030\007 \001(\t\022\r\n\005ctime\030\010 \001(\003" +
      "\022\016\n\006weight\030\t \001(\005\022\016\n\006action\030\n \001(\t\022\014\n\004pool" +
      "\030\013 \001(\005\022\r\n\005idStr\030\014 \001(\t\022\014\n\004attr\030\r \001(\005\022\021\n\ta" +
      "nimation\030\026 \001(\t\022!\n\010colorful\030\030 \001(\0162\017.DmCol" +
      "orfulType\"/\n\020DmSegMobileReply\022\033\n\005elems\030\001" +
      " \003(\0132\014.DanmakuElem*5\n\016DmColorfulType\022\014\n\010" +
      "NoneType\020\000\022\025\n\017VipGradualColor\020\341\324\003b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DanmakuElem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DanmakuElem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DanmakuElem_descriptor,
        new java.lang.String[] { "Id", "Progress", "Mode", "Fontsize", "Color", "MidHash", "Content", "Ctime", "Weight", "Action", "Pool", "IdStr", "Attr", "Animation", "Colorful", });
    internal_static_DmSegMobileReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DmSegMobileReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DmSegMobileReply_descriptor,
        new java.lang.String[] { "Elems", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
